float   = sign decimal exponent
sign    = ["+" / "-"]
decimal  = integer [dot fraction]
           / dot fraction
integer  = 1*%d48-57
dot      = "."
fraction = *%d48-57
exponent = ["e" esign exp]
esign    = ["+"ÿ/ "-"]
exp      = 1*%d48-57
